org: florianlepage
# "app" enables Serverless Framework Dashboard features and sharing them with other Services.
app: expense-api
service: expense-api

useDotenv: true

plugins:
    - serverless-offline

custom:
  serverless-offline:
    httpPort: 3000
    lambdaPort: 3002
    noPrependStageInUrl: true


provider:
  name: aws
  runtime: nodejs22.x
  region: eu-west-3
  environment:
    MONGODB_URI: ${env:MONGODB_URI}
    MONGODB_PASS: ${env:MONGODB_PASS}
    MONGODB_USER: ${env:MONGODB_USER}
    JWT_SECRET: ${env:JWT_SECRET}
    SECRET_TOKEN: ${env:SECRET_TOKEN}
    GOOGLE_SHEETS_ID: ${env:GOOGLE_SHEETS_ID}
    GOOGLE_PROJECT_ID: ${env:GOOGLE_PROJECT_ID}
    GOOGLE_PRIVATE_KEY_ID: ${env:GOOGLE_PRIVATE_KEY_ID}
    GOOGLE_PRIVATE_KEY: ${env:GOOGLE_PRIVATE_KEY}
    GOOGLE_CLIENT_EMAIL: ${env:GOOGLE_CLIENT_EMAIL}
    GOOGLE_CLIENT_ID: ${env:GOOGLE_CLIENT_ID}
    GOOGLE_AUTH_URI: ${env:GOOGLE_AUTH_URI}
    GOOGLE_TOKEN_URI: ${env:GOOGLE_TOKEN_URI}
    GOOGLE_AUTH_PROVIDER_X509_CERT_URL: ${env:GOOGLE_AUTH_PROVIDER_X509_CERT_URL}
    GOOGLE_CLIENT_X509_CERT_URL: ${env:GOOGLE_CLIENT_X509_CERT_URL}
    GOOGLE_UNIVERSE_DOMAIN: ${env:GOOGLE_UNIVERSE_DOMAIN}


functions:
  main:
    handler: dist/serverless.handler
    events:
        - http:
            method: ANY
            path: /
        - http:
            method: ANY
            path: '{proxy+}'